name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show Docker version
        run: docker --version

      - name: Run Docker
        run: docker run hello-world
